apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
spec:
  backoffLimit: 6
  completions: 20
  parallelism: 2
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo 'Hello I am from the Job;'
        image: busybox
        imagePullPolicy: Always
        name: busybox
      restartPolicy: Never
