apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipod
  name: multipod
spec:
  volumes:
  - name: log-dir
    emptyDir: {}
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c" ,"while true; do echo 'Hi I am from Main container'>> /var/log/index.html; sleep 5; done"]
    volumeMounts:
    - name: log-dir
      mountPath: /var/log
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: log-dir
      mountPath: /usr/share/nginx/html

