apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
  nodeSelector:
    boxName: docker-box
  tolerations:
    - effect: NoSchedule
      key: dedicated
      value: special-user
      operator: Equal
