apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: default
spec:
  containers:
    - image: busybox
      imagePullPolicy: Always
      name: busybox
      args:
        - /bin/sh
        - -c
        - sleep 1h
      volumeMounts:
        - name: sec-ctx-demo
          mountPath: /data/demo
      securityContext:
        allowPrivilegeEscalation: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: sec-ctx-demo
      emptyDir: {}
