apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - command: ["/bin/sh", "-c", "sleep 3600"]
      image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox
      resources:
        limits:
          cpu: 200m
          memory: 150Mi
        requests:
          cpu: 100m
          memory: 100Mi
