apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  containers:
    - command: ["wget", "-O-", "/workdir/index.html", "http://kubernetes.io"]
      image: busybox
      name: busybox
      volumeMounts:
        - name: workdir
          mountPath: /workdir
    - name: nginx
      image: nginx
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
