apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-06-08T05:07:55Z"
  labels:
    controller-uid: c6e1bba2-01c3-4b6b-8e6c-9e81aefdff77
    job-name: busybox2
  name: busybox2
  namespace: default
  selfLink: /apis/batch/v1/namespaces/default/jobs/busybox2
  uid: c6e1bba2-01c3-4b6b-8e6c-9e81aefdff77
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: c6e1bba2-01c3-4b6b-8e6c-9e81aefdff77
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: c6e1bba2-01c3-4b6b-8e6c-9e81aefdff77
        job-name: busybox2
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 30; echo world
        image: busybox
        imagePullPolicy: Always
        name: busybox2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
