apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis
    tier: server
  name: redis-service
spec:
  volumes:
    - name: data
      emptyDir: {}
    - name: config-volume
      configMap:
        name: redis-configmap
        items:
          - key: redis-config
            path: redis.conf
  containers:
    - env:
        - name: MASTER
          value: "true"
      image: redis
      name: redis-service
      command:
        - redis-server
        - "/redis-master/redis.conf"
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: data
          mountPath: /redis-master-data
        - name: config-volume
          mountPath: /redis-master
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 200m
          memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
